// Complete Team Members Data - Updated November 2025
// This is a temporary file containing all member data to be integrated into HubDetail.tsx

export function getMembers() {
  return [
    // ==========================================
    // CHILDHOOD AND GROWING UP HUB (10 members)
    // ==========================================
    
    // Faculty Members
    {
      name: 'Christine Tardif-Williams',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'ctardifwilliams@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University whose research focuses on childhood development, particularly in newcomer and racialized communities.',
      bioFr: 'Professeure à l\'Université Brock dont la recherche se concentre sur le développement de l\'enfance, particulièrement dans les communautés nouvelles arrivantes et racialisées.',
    },
    {
      name: 'Rebecca Raby',
      role: 'Professor, Hub Leader',
      roleFr: 'Professeure, Responsable du pôle',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'rraby@brocku.ca',
      type: 'faculty',
      isHubLeader: true,
      bio: 'Professor and Hub Leader at Brock University specializing in youth studies and the sociology of childhood.',
      bioFr: 'Professeure et responsable du pôle à l\'Université Brock, spécialisée dans les études sur la jeunesse et la sociologie de l\'enfance.',
    },
    {
      name: 'Dawn Trussell',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'dtrussell@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University whose research explores leisure, recreation, and family dynamics.',
      bioFr: 'Professeure à l\'Université Brock dont la recherche explore les loisirs, la récréation et la dynamique familiale.',
    },
    {
      name: 'Diane Farmer',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'University of Toronto',
      institutionFr: 'Université de Toronto',
      email: 'diane.farmer@utoronto.ca',
      type: 'faculty',
      bio: 'Professor at the University of Toronto whose research focuses on francophone minority education, immigration, and bilingualism.',
      bioFr: 'Professeure à l\'Université de Toronto dont la recherche se concentre sur l\'éducation en milieu francophone minoritaire, l\'immigration et le bilinguisme.',
    },
    
    // Students
    {
      name: 'Erika Alegria',
      role: 'PhD Student',
      roleFr: 'Étudiante au doctorat',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'ea21pd@brocku.ca',
      type: 'student',
      bio: 'PhD student at Brock University conducting research on childhood experiences and community engagement.',
      bioFr: 'Étudiante au doctorat à l\'Université Brock menant des recherches sur les expériences de l\'enfance et l\'engagement communautaire.',
    },
    {
      name: 'Frederick Oppong',
      role: 'PhD Student',
      roleFr: 'Étudiant au doctorat',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'Zw23la@brocku.ca',
      type: 'student',
      bio: 'PhD student at Brock University exploring childhood development and social inclusion. Implementation Council Student Rep.',
      bioFr: 'Étudiant au doctorat à l\'Université Brock explorant le développement de l\'enfance et l\'inclusion sociale. Représentant étudiant du Conseil de mise en œuvre.',
    },
    
    // Community Partners
    {
      name: 'Elisabeth Zimmermann',
      role: 'Executive Director',
      roleFr: 'Directrice exécutive',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'YWCA Niagara Region',
      institutionFr: 'YWCA Région de Niagara',
      email: 'ezimmermann@ywcaniagararegion.ca',
      type: 'community',
      bio: 'Executive Director of YWCA Niagara Region, providing leadership for shelter services, transitional housing, and support programs.',
      bioFr: 'Directrice exécutive de la YWCA Région de Niagara, assurant le leadership des services d\'hébergement, du logement transitoire et des programmes de soutien.',
    },
    {
      name: 'Emmanuel Mompongo',
      role: 'Project Coordinator',
      roleFr: 'Coordonnateur de projet',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'SOFIFRAN',
      institutionFr: 'SOFIFRAN',
      email: 'emmanuel@sofifran.org',
      type: 'community',
      bio: 'Project Coordinator at SOFIFRAN supporting francophone immigrant women and families in the Niagara region.',
      bioFr: 'Coordonnateur de projet à SOFIFRAN soutenant les femmes et les familles immigrantes francophones dans la région de Niagara.',
    },
    {
      name: 'Fété Ngira-Batware Kimpiobi',
      role: 'Community Partner',
      roleFr: 'Partenaire communautaire',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'SOFIFRAN',
      institutionFr: 'SOFIFRAN',
      email: 'info@sofifran.org',
      type: 'community',
      bio: 'Community partner with SOFIFRAN supporting francophone immigrant communities.',
      bioFr: 'Partenaire communautaire avec SOFIFRAN soutenant les communautés immigrantes francophones.',
    },
    {
      name: 'Mary Wiley',
      role: 'Director of Engagement',
      roleFr: 'Directrice de l\'engagement',
      hub: 'Childhood and Growing Up Hub',
      hubFr: 'Pôle Enfance et croissance',
      institution: 'Community Potential - Niagara Connects',
      institutionFr: 'Community Potential - Niagara Connects',
      email: 'mary.wiley@communitypotential.ca',
      type: 'community',
      bio: 'Director of Engagement at Community Potential - Niagara Connects, strengthening community connections and service coordination.',
      bioFr: 'Directrice de l\'engagement à Community Potential - Niagara Connects, renforçant les liens communautaires et la coordination des services.',
    },

    // ==========================================
    // HEALTH LITERACY HUB (21 members)
    // ==========================================
    
    // Faculty Members
    {
      name: 'Joanne Crawford',
      role: 'Professor, Hub Co-Leader',
      roleFr: 'Professeure, Co-responsable du pôle',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'joanne.crawford@brocku.ca',
      type: 'faculty',
      isHubLeader: true,
      bio: 'Professor and Hub Co-Leader at Brock University focusing on health literacy in immigrant and refugee populations.',
      bioFr: 'Professeure et co-responsable du pôle à l\'Université Brock, se concentrant sur la littératie en santé dans les populations immigrantes et réfugiées.',
    },
    {
      name: 'Farah Ahmad',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'York University',
      institutionFr: 'Université York',
      email: 'farahmad@yorku.ca',
      type: 'faculty',
      bio: 'Professor at York University conducting research on health equity and immigrant health.',
      bioFr: 'Professeure à l\'Université York menant des recherches sur l\'équité en santé et la santé des immigrants.',
    },
    {
      name: 'Wooksoo Kim',
      role: 'Professor',
      roleFr: 'Professeur',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'University at Buffalo',
      institutionFr: 'University at Buffalo',
      email: 'wkim5@buffalo.edu',
      type: 'faculty',
      bio: 'Professor at University at Buffalo specializing in community health and social work.',
      bioFr: 'Professeur à l\'University at Buffalo spécialisé dans la santé communautaire et le travail social.',
    },
    
    // Students & Research Assistants
    {
      name: 'Karlie Janes',
      role: 'Research Assistant',
      roleFr: 'Assistante de recherche',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'pi23le@brocku.ca',
      type: 'student',
      bio: 'Research Assistant at Brock University supporting health literacy research.',
      bioFr: 'Assistante de recherche à l\'Université Brock soutenant la recherche en littératie en santé.',
    },
    {
      name: 'Hurakhsh Hazheer',
      role: 'Research Assistant',
      roleFr: 'Assistant de recherche',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'vd22bu@brocku.ca',
      type: 'student',
      bio: 'Research Assistant at Brock University contributing to health literacy projects.',
      bioFr: 'Assistant de recherche à l\'Université Brock contribuant aux projets de littératie en santé.',
    },
    
    // Community Partners
    {
      name: 'Marie Mouradikian',
      role: 'Executive Director/CEO',
      roleFr: 'Directrice exécutive/PDG',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Bridges Niagara',
      institutionFr: 'Bridges Niagara',
      email: 'mmouradikian@bridgesniagara.ca',
      type: 'community',
      bio: 'Executive Director/CEO of Bridges Niagara, supporting newcomer integration and settlement services.',
      bioFr: 'Directrice exécutive/PDG de Bridges Niagara, soutenant l\'intégration et les services d\'établissement pour les nouveaux arrivants.',
    },
    {
      name: 'Ijeoma Michael',
      role: 'Girls and Womens\' Projects Lead',
      roleFr: 'Responsable des projets pour les filles et les femmes',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Future Black Female',
      institutionFr: 'Future Black Female',
      email: 'ijeoma@futureblackfemale.com',
      type: 'community',
      bio: 'Girls and Womens\' Projects Lead at Future Black Female, empowering Black girls and women.',
      bioFr: 'Responsable des projets pour les filles et les femmes à Future Black Female, autonomisant les filles et les femmes noires.',
    },
    {
      name: 'Mariam Khayinza',
      role: 'Project Coordinator, Hub Co-Leader',
      roleFr: 'Coordonnatrice de projet, Co-responsable du pôle',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'TOES Niagara',
      institutionFr: 'TOES Niagara',
      email: 'mariam@toesniagara.ca',
      type: 'community',
      isHubLeader: true,
      bio: 'Project Coordinator and Hub Co-Leader at TOES Niagara, leading community health initiatives.',
      bioFr: 'Coordonnatrice de projet et co-responsable du pôle à TOES Niagara, dirigeant les initiatives de santé communautaire.',
    },
    {
      name: 'Mary Wiley',
      role: 'Director of Engagement',
      roleFr: 'Directrice de l\'engagement',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Community Potential - Niagara Connects',
      institutionFr: 'Community Potential - Niagara Connects',
      email: 'mary.wiley@communitypotential.ca',
      type: 'community',
      bio: 'Director of Engagement at Community Potential - Niagara Connects.',
      bioFr: 'Directrice de l\'engagement à Community Potential - Niagara Connects.',
    },
    {
      name: 'Nyarai Kapisavanhu',
      role: 'Executive Director',
      roleFr: 'Directrice exécutive',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'TOES Niagara',
      institutionFr: 'TOES Niagara',
      email: 'nyarai@toesniagara.ca',
      type: 'community',
      bio: 'Executive Director of TOES Niagara, supporting immigrant and refugee health.',
      bioFr: 'Directrice exécutive de TOES Niagara, soutenant la santé des immigrants et des réfugiés.',
    },
    {
      name: 'Shelby Cleveland',
      role: 'Health Promoter',
      roleFr: 'Promoteur de la santé',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Niagara Falls Community Health Center',
      institutionFr: 'Centre de santé communautaire de Niagara Falls',
      email: 'scleveland@nfchc.ca',
      type: 'community',
      bio: 'Health Promoter at Niagara Falls Community Health Center.',
      bioFr: 'Promoteur de la santé au Centre de santé communautaire de Niagara Falls.',
    },
    {
      name: 'Ailish Westaway',
      role: 'Health Promoter',
      roleFr: 'Promoteur de la santé',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'QUEST Community Health Center',
      institutionFr: 'Centre de santé communautaire QUEST',
      email: 'awestaway@questchc.ca',
      type: 'community',
      bio: 'Health Promoter at QUEST Community Health Center.',
      bioFr: 'Promoteur de la santé au Centre de santé communautaire QUEST.',
    },
    {
      name: 'Zainab Awad',
      role: 'Manager Diversity, Equity and Inclusion',
      roleFr: 'Gestionnaire Diversité, Équité et Inclusion',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Niagara Health System',
      institutionFr: 'Système de santé de Niagara',
      email: 'zainab.awad@niagarahealth.on.ca',
      type: 'community',
      bio: 'Manager of Diversity, Equity and Inclusion at Niagara Health System.',
      bioFr: 'Gestionnaire de la diversité, de l\'équité et de l\'inclusion au Système de santé de Niagara.',
    },
    {
      name: 'Donna Mills',
      role: 'Team Lead Health Promotion',
      roleFr: 'Chef d\'équipe Promotion de la santé',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Niagara Public Health',
      institutionFr: 'Santé publique de Niagara',
      email: 'donna.mills@niagararegion.ca',
      type: 'community',
      bio: 'Team Lead for Health Promotion at Niagara Public Health.',
      bioFr: 'Chef d\'équipe pour la promotion de la santé à Santé publique de Niagara.',
    },
    {
      name: 'Karen Schmidt',
      role: 'Service System & Performance Management Advisor',
      roleFr: 'Conseillère en gestion des systèmes de services et de la performance',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'Niagara Region Children\'s Services',
      institutionFr: 'Services à l\'enfance de la région de Niagara',
      email: 'Karen.Schmidt@niagararegion.ca',
      type: 'community',
      bio: 'Service System & Performance Management Advisor for Children\'s Services at Niagara Region.',
      bioFr: 'Conseillère en gestion des systèmes de services et de la performance pour les services à l\'enfance de la région de Niagara.',
    },
    {
      name: 'Holly Jones',
      role: 'Manager, Programming & Promotions',
      roleFr: 'Gestionnaire, Programmation et promotions',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'St. Catharines Library',
      institutionFr: 'Bibliothèque de St. Catharines',
      email: 'hjones@myscpl.ca',
      type: 'community',
      bio: 'Manager of Programming & Promotions at St. Catharines Library.',
      bioFr: 'Gestionnaire de la programmation et des promotions à la bibliothèque de St. Catharines.',
    },
    {
      name: 'Melissa Broere',
      role: 'Branch Librarian',
      roleFr: 'Bibliothécaire de succursale',
      hub: 'Health Literacy Hub',
      hubFr: 'Pôle Littératie en santé',
      institution: 'St. Catharines Library',
      institutionFr: 'Bibliothèque de St. Catharines',
      email: 'mbroere@myscpl.ca',
      type: 'community',
      bio: 'Branch Librarian at St. Catharines Library.',
      bioFr: 'Bibliothécaire de succursale à la bibliothèque de St. Catharines.',
    },

    // ==========================================
    // IDENTITY, CONNECTIONS AND BELONGING HUB (19 members)
    // ==========================================
    
    // Faculty Members
    {
      name: 'Jean Ntakirutimana',
      role: 'Professor, Hub Leader',
      roleFr: 'Professeur, Responsable du pôle',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'jntakirutimana@brocku.ca',
      type: 'faculty',
      isHubLeader: true,
      bio: 'Professor and Hub Leader at Brock University, leading research on identity and belonging in Afro-descendant communities.',
      bioFr: 'Professeur et responsable du pôle à l\'Université Brock, dirigeant la recherche sur l\'identité et l\'appartenance dans les communautés afro-descendantes.',
    },
    {
      name: 'Julie Ham',
      role: 'Professor, Project Leader',
      roleFr: 'Professeure, Responsable de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'jham@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University and Project #2 Leader focusing on migrant farmworkers in community.',
      bioFr: 'Professeure à l\'Université Brock et responsable du projet #2 se concentrant sur les travailleurs agricoles migrants dans la communauté.',
    },
    {
      name: 'Dane Marco Di Cesare',
      role: 'Professor, Project Leader',
      roleFr: 'Professeur, Responsable de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'ddicesare@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University and Project #3 Leader researching ICT use and SGD newcomers.',
      bioFr: 'Professeur à l\'Université Brock et responsable du projet #3 étudiant l\'utilisation des TIC et les nouveaux arrivants de diverses identités sexuelles et de genre.',
    },
    {
      name: 'Pascal Lupien',
      role: 'Professor',
      roleFr: 'Professeur',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'plupien@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University contributing to research on identity and community connections.',
      bioFr: 'Professeur à l\'Université Brock contribuant à la recherche sur l\'identité et les connexions communautaires.',
    },
    {
      name: 'Shelley Craig',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'University of Toronto',
      institutionFr: 'Université de Toronto',
      email: 'shelley.craig@utoronto.ca',
      type: 'faculty',
      bio: 'Professor at the University of Toronto specializing in social work and LGBTQ+ communities.',
      bioFr: 'Professeure à l\'Université de Toronto spécialisée dans le travail social et les communautés LGBTQ+.',
    },
    {
      name: 'Kaschka Watson',
      role: 'Professor',
      roleFr: 'Professeure',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'kwatson@brocku.ca',
      type: 'faculty',
      bio: 'Professor at Brock University conducting research on identity and belonging.',
      bioFr: 'Professeure à l\'Université Brock menant des recherches sur l\'identité et l\'appartenance.',
    },
    {
      name: 'Dr. Jennifer Holzer',
      role: 'Post Doctoral Fellow',
      roleFr: 'Boursière postdoctorale',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University - Environmental Sustainability Research Centre',
      institutionFr: 'Université Brock - Centre de recherche sur la durabilité environnementale',
      email: 'jholzer@brocku.ca',
      type: 'faculty',
      bio: 'Post Doctoral Fellow at Brock University Environmental Sustainability Research Centre.',
      bioFr: 'Boursière postdoctorale au Centre de recherche sur la durabilité environnementale de l\'Université Brock.',
    },
    {
      name: 'Dr. Winston Benn',
      role: 'Post Doctoral Fellow',
      roleFr: 'Boursier postdoctoral',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'CARICOM',
      institutionFr: 'CARICOM',
      email: 'bennwcnd@gmail.com',
      type: 'faculty',
      bio: 'Incoming Canada/Caricom Researcher and Post Doctoral Fellow.',
      bioFr: 'Chercheur Canada/Caricom entrant et boursier postdoctoral.',
    },
    
    // Students & Research Assistants
    {
      name: 'Justin Mafie',
      role: 'Undergraduate Research Assistant, Webmaster',
      roleFr: 'Assistant de recherche de premier cycle, Webmestre',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Brock University',
      institutionFr: 'Université Brock',
      email: 'jmafie@brocku.ca',
      type: 'student',
      bio: 'Undergraduate Research Assistant and Webmaster at Brock University.',
      bioFr: 'Assistant de recherche de premier cycle et webmestre à l\'Université Brock.',
    },
    
    // Community Partners
    {
      name: 'Emmanuel Mompongo',
      role: 'Project Coordinator',
      roleFr: 'Coordonnateur de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'SOFIFRAN',
      institutionFr: 'SOFIFRAN',
      email: 'emmanuel@sofifran.org',
      type: 'community',
      bio: 'Project Coordinator at SOFIFRAN supporting francophone immigrant communities.',
      bioFr: 'Coordonnateur de projet à SOFIFRAN soutenant les communautés immigrantes francophones.',
    },
    {
      name: 'Fété Ngira-Batware Kimpiobi',
      role: 'Community Partner',
      roleFr: 'Partenaire communautaire',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'SOFIFRAN',
      institutionFr: 'SOFIFRAN',
      email: 'info@sofifran.org',
      type: 'community',
      bio: 'Community partner with SOFIFRAN.',
      bioFr: 'Partenaire communautaire avec SOFIFRAN.',
    },
    {
      name: 'Franklin Weledji',
      role: 'Community Liaison Officer',
      roleFr: 'Agent de liaison communautaire',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Centre canadien pour L\'unite de la famille (CCF)',
      institutionFr: 'Centre canadien pour L\'unite de la famille (CCF)',
      email: 'fleukam@cscmonavenir.ca',
      type: 'community',
      bio: 'Community Liaison Officer at Centre canadien pour L\'unite de la famille (CCF).',
      bioFr: 'Agent de liaison communautaire au Centre canadien pour L\'unite de la famille (CCF).',
    },
    {
      name: 'Janet Madume',
      role: 'Executive Director',
      roleFr: 'Directrice exécutive',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Bridges Niagara - Immigrant and Refugee Services',
      institutionFr: 'Bridges Niagara - Services pour immigrants et réfugiés',
      email: 'jmadume@wellandheritagecouncil.com',
      type: 'community',
      bio: 'Executive Director of Bridges Niagara - Immigrant and Refugee Services.',
      bioFr: 'Directrice exécutive de Bridges Niagara - Services pour immigrants et réfugiés.',
    },
    {
      name: 'Lori Webster',
      role: 'IEHP Hub Pilot/Labour Market Orientation',
      roleFr: 'Pilote du pôle IEHP/Orientation du marché du travail',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Bridges Niagara - Immigrant and Refugee Services',
      institutionFr: 'Bridges Niagara - Services pour immigrants et réfugiés',
      email: 'lwebster@wellandheritagecouncil.com',
      type: 'community',
      bio: 'IEHP Hub Pilot and Labour Market Orientation specialist at Bridges Niagara.',
      bioFr: 'Pilote du pôle IEHP et spécialiste de l\'orientation du marché du travail à Bridges Niagara.',
    },
    {
      name: 'Mariam Khayinza',
      role: 'Project Coordinator',
      roleFr: 'Coordonnatrice de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'TOES Niagara',
      institutionFr: 'TOES Niagara',
      email: 'mariam@toesniagara.ca',
      type: 'community',
      bio: 'Project Coordinator at TOES Niagara.',
      bioFr: 'Coordonnatrice de projet à TOES Niagara.',
    },
    {
      name: 'Mary Wiley',
      role: 'Director of Engagement',
      roleFr: 'Directrice de l\'engagement',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Community Potential - Niagara Connects',
      institutionFr: 'Community Potential - Niagara Connects',
      email: 'mary.wiley@communitypotential.ca',
      type: 'community',
      bio: 'Director of Engagement at Community Potential - Niagara Connects.',
      bioFr: 'Directrice de l\'engagement à Community Potential - Niagara Connects.',
    },
    {
      name: 'Mikhaela Sullivan',
      role: 'Project Officer',
      roleFr: 'Agente de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Le Réseau en Immigration Francophone du Centre-Sud-Ouest de l\'Ontario',
      institutionFr: 'Le Réseau en Immigration Francophone du Centre-Sud-Ouest de l\'Ontario',
      email: 'mikhaela.sullivan@cschn.ca',
      type: 'community',
      bio: 'Project Officer at Le Réseau en Immigration Francophone du Centre-Sud-Ouest de l\'Ontario.',
      bioFr: 'Agente de projet au Réseau en Immigration Francophone du Centre-Sud-Ouest de l\'Ontario.',
    },
    {
      name: 'Nyarai Kapisavanhu',
      role: 'Executive Director',
      roleFr: 'Directrice exécutive',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'TOES Niagara',
      institutionFr: 'TOES Niagara',
      email: 'nyarai@toesniagara.ca',
      type: 'community',
      bio: 'Executive Director of TOES Niagara.',
      bioFr: 'Directrice exécutive de TOES Niagara.',
    },
    {
      name: 'Daniel Tatarnic',
      role: 'Reverend Dr.',
      roleFr: 'Révérend Dr.',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Migrant Farm Workers Project: St. Alban\'s Anglican Church',
      institutionFr: 'Projet des travailleurs agricoles migrants : Église anglicane St. Alban',
      email: 'danieltatarnic@outlook.com',
      type: 'community',
      bio: 'Reverend Dr. at Migrant Farm Workers Project supporting seasonal agricultural workers.',
      bioFr: 'Révérend Dr. au Projet des travailleurs agricoles migrants soutenant les travailleurs agricoles saisonniers.',
    },
    {
      name: 'Amy Andrews',
      role: 'Research Analyst',
      roleFr: 'Analyste de recherche',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Niagara Local Immigration Partnership',
      institutionFr: 'Partenariat local en immigration de Niagara',
      email: 'amy.andrews@niagararegion.ca',
      type: 'community',
      bio: 'Research Analyst at Niagara Local Immigration Partnership.',
      bioFr: 'Analyste de recherche au Partenariat local en immigration de Niagara.',
    },
    {
      name: 'Lisa Garlent',
      role: 'Project Coordinator',
      roleFr: 'Coordonnatrice de projet',
      hub: 'Identity, Connections and Belonging Hub',
      hubFr: 'Pôle Identité, relations et appartenance',
      institution: 'Niagara Local Immigration Partnership',
      institutionFr: 'Partenariat local en immigration de Niagara',
      email: 'lisa.garlent@niagararegion.ca',
      type: 'community',
      bio: 'Project Coordinator at Niagara Local Immigration Partnership.',
      bioFr: 'Coordonnatrice de projet au Partenariat local en immigration de Niagara.',
    },
  ];
}